name: Build and push to Docker
on:
  push:
    tags:
    - 'v*'
    - '!v*-beta'

jobs:
  random_num:
    env:
      IMAGE_NAME: chukmunnlee/randnum:${{ github.ref_name }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    #if: ! contains(github.event.head_commit.message, "#NORUN#")
    runs-on: ubuntu-latest
    steps:
    - name: Echo message  
      run: echo ">>> commit: ${{ (github.event.head_commit.message }}"
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Get short hash
      id: get_commit_id
      run: echo "::set-output name=shorthash::$(git rev-parse --short HEAD)"
    - name: Build image and push to Docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}
        #tags: chukmunnlee/randnum:${{ steps.get_commit_id.outputs.shorthash }}
    - name: Push notification to slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "Pushed build to Dockerhub: ${{ env.IMAGE_NAME }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: Fred Flintstone\nMatriculation: abc123\nEmail: fred@gmail.com\nRepo: https://github.com/${{ github.repository }}\nImage name: ${{ env.IMAGE_NAME }}\nImage url: https://hub.docker.com/repository/docker/chukmunnlee/randnum"
                }
              }
            ]
          }
