name: Build and push to Docker
on:
  push:
    tags:
    - 'v*'
    - '!v*-beta'

jobs:
  random_num:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Get short commit id
      id: get_commit_id
      run: echo "::set-output name=shorthash::$(git rev-parse --short HEAD)"
    - name: Echo image tag
      run: echo "${{ steps.get_commit_id.outputs.shorthash }}"
    - name: Login to Docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image and push to Docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: chukmunnlee/randnum:${{ steps.get_commit_id.outputs.shorthash }}
